# Generated by Django 4.0.3 on 2022-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateTimeField(verbose_name='date')),
                ('detail', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
